id: I6F9FC4BB
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:32:19.447082
last_modified: 2023-02-10 00:32:19.447239
source_metadata:
  title: 'N훮g훮rjuna: Ratn훮val카'
  language: bo
bases:
  B805:
    base_file: B805.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
